### ISSUE TITLE
May I use code from roing.us in my own personal software projects?

### ISSUE THREAD

**Issue by veliebm** [SplitPixl/roingus#3]
Hi!

I stumbled on roing.us a while back and kinda fell in love with it. My friends and I think it's really funny. As a joke, I made [my own version of it for my personal site](https://benvelie.com/ben.html) except in my version you click a silly picture of me and the site also talks to a backend so users can see global observation time and click count. Source code is [here](https://github.com/veliebm/squeaker).

I've started to get interested in contributing to FOSS projects, so I've been learning more about licensing software repositories. Looking in the [roingus repo](https://github.com/SplitPixl/roingus), I realized just now that it's unlicensed, meaning that I shouldn't have used its code without asking you for permission.

So, I'm coming to you with a request:
- If you're comfortable with doing so, could you please add a LICENSE to your repository allowing its free use? Maybe the MIT license would work?
- If not, could you please give me permission to use your code from that project?

I could also take down my webpage if you'd like - you'd be well within your legal rights to ask me to do that, although I hope you don't :)

Hope to hear from you soon,

Ben

**Comment by SplitPixl** [comment]
Hello!

Thank you for your interest in this website!  I'm glad it could be a resource for fun.  I've gone ahead and added a license, and your use case should be covered by it.  My goal in releasing this code is to encourage people to learn and collaborate to spread fun together.  I'd appreciate if you contributed to the repository, but it's not required.

SplitPixl

**Comment by veliebm** [comment]
Thanks! I actually am interested in contributing to this repo. What work needs doing?

**Comment by SplitPixl** [comment]
make roingus real
________________________________
